image: nixos/nix:latest

before_script:
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
  - nix-channel --update

build_infrastructure:
  stage: build
  script:
    - nix-build default.nix

integration_test:
  stage: test
  dependencies:
    - build_infrastructure
  script:
    - cd ./integration_test
    - nix-build default.nix
    - ./result
